title: Word to PDF Converter
description: Convert Word documents to PDFs instantly with this simple web tool.
baseurl: "" # Keep this empty unless your site is in a subdirectory
url: "https://RoyDev72.github.io" # Change this to your GitHub Pages URL if different

# Build settings
theme: minima # or your chosen theme like 'jekyll-theme-primer'
markdown: kramdown

# Don't process these files/folders
exclude:
  - node_modules
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - .gitignore

# GitHub Pages config
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: custom settings
permalink: pretty
